CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2
TARGET = build\bob.exe
SOURCE = main.cpp

all: $(TARGET)

$(TARGET): $(SOURCE)
	if not exist build mkdir build
	$(CXX) $(CXXFLAGS) $(SOURCE) -o $(TARGET)

clean:
	if exist build rmdir /s /q build

run: $(TARGET)
	$(TARGET) examples\examples.bob

repl: $(TARGET)
	$(TARGET)

.PHONY: all clean run repl